### ISSUE TITLE
Add to maven Central Repository

### ISSUE THREAD

**Issue by ChrisMCMine** [FaizMalkani/FloatingActionButton#9]
Please add FAB to the Maven Central, makes it easier to manage dependencies with gradle.

**Comment by mikeholler** [comment]
@FaizMalkani why was this closed? Do you intent to put this on Maven Central or JCenter?

**Comment by FaizMalkani** [comment]
@mikeholler , yes I'm working on some code cleanup, following which I'll push it to Maven Central
